[package]
name = "npb-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.6.1"

[features]
S = ["CLASS"]
W = ["CLASS"]
A = ["CLASS"]
B = ["CLASS"]
C = ["CLASS"]
D = ["CLASS"]
CLASS = []